name: iOS starter workflow               
on:             
  push:       
    branches:           
      - main                  
  pull_request:    
    branches:    
      - main  

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 

jobs:
  build: 
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-12

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Ruby Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Apple Certificate and Provisioning Profile
        env:
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: |
          security create-keychain -p "" build.keychain
          security import Certificates.p12 -k ~/Library/Keychains/build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp DemoTest.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Install CocoaPods Dependencies
        run: |
          sudo gem install cocoapods
          cd SignIn
          pod install

      - name: Navigate to Project Directory
        run: cd SignIn

      - name: Update Provisioning Profile Specifier
        run: |
         ruby -e "require 'xcodeproj'; \
           project_path = 'SignIn/SignIn.xcodeproj'; \
           project = Xcodeproj::Project.open(project_path); \
           project.targets.each do |target| \
             target.build_configurations.each do |config| \
               config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = 'DemoTest'; \
             end; \
           end; \
           project.save"
        shell: bash


      - name: List Available Simulators
        run: xcrun simctl list devices available     

      - name: Build and Archive for Real Device
        run: |
         xcodebuild archive -workspace SignIn.xcworkspace \
         -scheme SignIn -archivePath "$RUNNER_TEMP/SignIn.xcarchive" \
         -sdk iphoneos -configuration Debug \
         clean archive DEVELOPMENT_TEAM="X372X3URRM" \
         PROVISIONING_PROFILE_SPECIFIER="DemoTest" -allowProvisioningUpdates

      - name: List Files in Temporary Directory
        run: |
          ls -a "$RUNNER_TEMP"
          ls -a "$RUNNER_TEMP/SignIn.xcarchive"
          ls -a "$RUNNER_TEMP/SignIn.xcarchive/Products/Applications/"

      - name: Export IPA
        run: |
          xcodebuild -archivePath "$RUNNER_TEMP/SignIn.xcarchive" \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath "$RUNNER_TEMP/build" \
                     -allowProvisioningUpdates \
                     -exportArchive \
                     | tee build_output.txt
